name: Deploy Chatterly-Renewed to VPS

on:
  push:
    branches:
      - main  # Cambia a 'master' si tu rama principal se llama así

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploying via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/ChatterlyRenewed
            git pull origin main
            docker-compose up -d --build app